[package]
name = "araucaria_plugins"
version = "1.0.0"
edition = "2021"
license = "AGPL-3.0"
authors = ["João Arthur <joaoarthurlf.dev@gmail.com>"]

[lib]
crate-type = ["rlib"]

[features]

[dependencies]
araucaria = { git = "https://github.com/joao-arthur/araucaria", rev = "160b750033049c9e8bb87c29e658d29719482967" }
email_address = "0.2.9"
unicode-segmentation = "1.12.0"
regex = "1.11.1"
serde_json = "1.0.140"
serde = "1.0.219"

[dev-dependencies]
rocket = { version = "0.5.1", features = ["json"] }
