[package]
name = "araucaria_plugins"
version = "1.0.0"
edition = "2021"

license = "AGPL-3.0"

[lib]
crate-type = ["rlib"]
bench = false

[dependencies]
araucaria = { git = "https://github.com/joao-arthur/araucaria", rev = "251a8e64f67292fd0908c15542745df23a8d9efe" }
email_address = "0.2.9"
regex = "1.11.1"
serde_json = "1.0.140"
serde = "1.0.219"

[dev-dependencies]
rocket = { version = "0.5.1", features = ["json"] }
